### ISSUE TITLE
CStoCS_Pitch is not found

### ISSUE THREAD

**Issue by ChefOtter** [chaolmu/youBot_trajectory_ros#1]
Hey Chao,
I try to work with youBot_trajectory_library, i am getting error.
I cloned your github repository into catkin_ws/src and executed command **catkin_make**
But i am getting following error.
```
/catkin_ws/src/youBot_trajectory_ros/src/draw_square_test.cpp:7:47: fatal error: trajectory_generator/CStoCS_Pitch.h: No such file or directory
 #include <trajectory_generator/CStoCS_Pitch.h>
                                               ^
compilation terminated.
```
Also i looked after **CStoCS_Pitch.h** File in my computer, there is no such file.
Do you know why am i getting this error? 
Thanks in advance
Regards

**Comment by chaolmu** [comment]
@ChefOtter you should install the dependency: https://github.com/chaolmu/rpg_youbot_torque_control.git, which I have modified from rpg_youbot_torque_control. CStoCS_Pitch service is one of several features which I added to trajectory generator.
