### ISSUE TITLE
couldn't call service 

### ISSUE THREAD

**Issue by ChefOtter** [chaolmu/youBot_trajectory_ros#2]
Hi chaolmu,
I try to work within you package, there is some issue with it.
When I execute `roslaunch youbot_draw traj_service.launch` after then I execute `rosrun youbot_draw draw_TU_logo`, it shows me `could't call service` 
but if I execute `rosrun youbot_draw draw_circle`, it shows me `CS 2 CS not feasible`
In the other hand if I use old youBot_trajectory_ros package, it works again.
I wanna say, it could some  bug or something.
Maybe you know, why am I getting this errors?
thank you in advance
best regards

**Comment by chaolmu** [comment]
@ChefOtter can you give me more details: which service cannot be called? First of all check if trajectory service is running.

**Comment by ChefOtter** [comment]
@chaolmu 
I will try to explain step by step
**Before Update or changes**
 I cloned your package `youBot_trajectory_ros` and this package `rpg_youbot_torque_control` 
It worked fine.

**After Update or changes**
I cloned again same packages in my workspace. In new version of your package,
which you updated or made some changes. In the ws I execute `catkin_make`,  it can't generate `CStoCS_Pitch.h`. I am getting following error.
`trajectory_generator/CStoCS_Pitch.h: No such file or directory
 #include <trajectory_generator/CStoCS_Pitch.h>`
As a solution, I kept also my old files, i copied just content of `trajectory_generator` folder from my old files and paste it in new `trajectory_generator` folder under `catkin_ws/devel/include/trajectory_generator`.
I solved this problem like this :+1: 
But in the terminal, if I execute `roslaunch youbot_draw traj_service.launch` 
here is the output for this command:

```
NODES
  /
    ik_solver_service (ik_solver_service/ik_solver_service)
    trajectory_generator (trajectory_generator/trajectory_service)

auto-starting new master
process[master]: started with pid [6574]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ce79ef84-20f4-11e6-b49c-000c29fed1c5
process[rosout-1]: started with pid [6587]
started core service [/rosout]
process[ik_solver_service-2]: started with pid [6590]
process[trajectory_generator-3]: started with pid [6600]
[ INFO] [1464014649.588944198]: Ready to process trajectory requests
Rotation
1 0 0
0 1 0
0 0 1
Transforming CS to JS Trajectory, this might take a while
fully constrained not feasible
[ INFO] [1464015792.193049624]: Trajectory Generator trajectories generated
```

Normally it should be like this:
```
NODES
  /
    ik_solver_service (ik_solver_service/ik_solver_service)
    trajectory_generator (trajectory_generator/trajectory_service)

auto-starting new master
process[master]: started with pid [20559]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 42b4d786-20f7-11e6-b326-000c2955e3f3
process[rosout-1]: started with pid [20572]
started core service [/rosout]
process[ik_solver_service-2]: started with pid [20575]
process[trajectory_generator-3]: started with pid [20581]
[ INFO] [1464015703.860739603]: IK Solver Ready
[ INFO] [1464015703.861611917]: Trajectory Generator Ready
```

and in other terminal I execute `rosrun youbot_draw draw_TU_logo`
```
rosrun youbot_draw draw_TU_logo 
[ INFO] [1464014656.745872335]: max_vel: 0.100000 	 max_acc :0.500000
[ INFO] [1464014656.746000861]: Generating trajectories, please wait...
[ERROR] [1464014656.747124782]: Could not call service.
```

If I execute following command:
```
rosrun youbot_draw draw_circle 
CS 2 CS not feasible
```
Before update or changes everything was working very well.
Now just some kind of problems occured.
I think so, it will help was I wrote. I think so, it can't call `traj_service`
ps: I cloned old files of the package, it is working now, just it is not working with new version.
Best Regards

**Comment by chaolmu** [comment]
@ChefOtter 
I have changed traj_service and ik_solver_service from torque package to a standalone package called youbot_common. 
Git pull the latest version of youbot_common and youbot_trajectory_ros, then try again.
Best regards.

**Comment by ChefOtter** [comment]
@chaolmu 
I tried it works fine. But in `circle.cpp` File, you used following part, i don't why,
```
<<<<<<< HEAD
=======
>>>>>>> a993bacd10323ca5cb1bc577ddb76f29823e7747
```
if I build my ws with catkin_make it gives error just for you information. i just commented out this sections, which inclueded `HEAD` staff, then i made catkin_make. It can build without error.
:+1:

**Comment by chaolmu** [comment]
it is something trash. I think it was added by git because of some git-error. just delete it
